title: ricallan.uk
description: Information about Richard Allan
repository: regulate-tech/ricallan
plugins:
  - jekyll-remote-theme
# remote_theme: pages-themes/tactile
permalink: /posts/:year/:month/:day/:title/

# URL settings for GitHub Pages testing
# Needs editing when moving to external domain
baseurl: "/ricallan"  # Your repository name with leading slash
url: "https://regulate-tech.github.io"  # Your GitHub Pages URL

# Hide GitHub repository information
github_username: # leave blank
repository: # leave blank
show_downloads: false
github:
  is_project_page: false
  is_user_page: false

# Disable repository link
public: false
