title: ricallan.uk
description: Information about Richard Allan
repository: regulate-tech/ricallan
plugins:
  - jekyll-remote-theme
remote_theme: pages-themes/tactile
permalink: /posts/:year/:month/:day/:title/